name: bian_app
description: BIAN - Bienestar Animal App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  
  http: ^1.2.2
  dio: ^5.9.0
  
  flutter_secure_storage: ^8.1.0
  shared_preferences: ^2.5.3
  
  provider: ^6.1.5
  connectivity_plus: ^6.1.3
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  google_fonts: ^6.3.2
  lottie: ^2.7.0
  flutter_svg: ^2.2.1
  
  validators: ^3.0.0
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4
  uuid: ^4.5.1
  
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  device_info_plus: ^12.2.0
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo2.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo2.png"